packages:
  - "apps/*"
  - "packages/*"

overrides:
  "@tiptap/core": "2.27.2"
  "@tiptap/pm": "2.27.2"
  "@tiptap/starter-kit": "2.27.2"
  "@tiptap/extension-horizontal-rule": "2.27.2"
  "@tiptap/extension-link": "2.27.2"
  "fast-jwt": "^6.2.4"
  "tinymce": "^7.9.3"
  "fast-uri": "^3.1.2"
  "i18next-http-backend": "^3.0.5"
  "uuid": "^11.1.1"
  "postcss": "^8.5.10"
  "esbuild": "^0.25.0"

